# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jsivanes <jsivanes@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/11/06 16:56:11 by jsivanes          #+#    #+#              #
#    Updated: 2016/01/15 08:57:04 by jsivanes         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_advanced_do-op
SRC = printf.c operateur.c do_op.c ft_atoi.c
FLAG = -Wall -Wextra -Werror
OPTION = -o $(NAME)

all: 
	gcc $(OPTION) $(FLAG) $(SRC)

clean:
	/bin/rm -f $(NAME)

re: clean all
